build:
	javac Bani.java
	javac Gard.java
	javac Bomboane.java
	javac Sala.java

run-p1:
	java Bani.class

run-p2:
	java Gard.class

run-p3:
	java Bomboane.class

run-p4:
	java Sala.class

clean:
	rm Bani, Gard, Bomboane, Sala
